#pragma once

enum ParticleType {
	PARTICLE_BLOCKCRACK = 1,
	PARTICLE_CRIT,
	PARTICLE_SMOKE,
	PARTICLE_CLOUD,
	PARTICLE_FLAME,
	PARTICLE_LAVA,
	PARTICLE_REDSTONE,
	PARTICLE_ITEMCRACK,
	PARTICLE_SNOWBALLPOOF,
	PARTICLE_MOBFLAME,
	PARTICLE_HEART
};
