/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ksymc_forgepe_ModManager */

#ifndef _Included_com_ksymc_forgepe_ModManager
#define _Included_com_ksymc_forgepe_ModManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ksymc_forgepe_ModManager
 * Method:    nativeLoadMod
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ksymc_forgepe_ModManager_nativeLoadMod
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_ksymc_forgepe_ModManager
 * Method:    nativeInitialization
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ksymc_forgepe_ModManager_nativeInitialization
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
